# Generated by Django 3.0 on 2020-09-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.IntegerField(default=0),
        ),
    ]
