# Generated by Django 3.0 on 2020-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200923_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
