# Generated by Django 3.0 on 2020-09-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200927_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
