# Generated by Django 3.0 on 2021-01-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20201231_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
